<wsdl:definitions
     name="DB_SOURCE"
     targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/ASSIGNMENTS_VENGAIAH/DB_SELECT_INSERT_DB_ADAPTER_P4/DB_SOURCE"
     xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/ASSIGNMENTS_VENGAIAH/DB_SELECT_INSERT_DB_ADAPTER_P4/DB_SOURCE"
     xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/"
     xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/"
     xmlns:top="http://xmlns.oracle.com/pcbpel/adapter/db/top/DB_SOURCE"
     xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    >
  <plt:partnerLinkType name="DB_SOURCE_plt" >
    <plt:role name="DB_SOURCE_role" >
      <plt:portType name="tns:DB_SOURCE_ptt" />
    </plt:role>
  </plt:partnerLinkType>
    <wsdl:types>
      <schema xmlns="http://www.w3.org/2001/XMLSchema" >
        <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/top/DB_SOURCE" schemaLocation="../Schemas/DB_SOURCE_table.xsd" />
      </schema>
    </wsdl:types>
    <wsdl:message name="DB_SOURCESelect_inputParameters">
        <wsdl:part name="DB_SOURCESelect_inputParameters" element="top:DB_SOURCESelect_cusidInputParameters"/>
    </wsdl:message>
    <wsdl:message name="CustomersCollection_msg">
        <wsdl:part name="CustomersCollection" element="top:CustomersCollection"/>
    </wsdl:message>
    <wsdl:portType name="DB_SOURCE_ptt">
        <wsdl:operation name="DB_SOURCESelect">
            <wsdl:input message="tns:DB_SOURCESelect_inputParameters"/>
            <wsdl:output message="tns:CustomersCollection_msg"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>
