<wsdl:definitions
     name="READ_FILE"
     targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/file/ASSIGNMENTS_VENGAIAH/FTP_ADAPTER_P2/READ_FILE"
     xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/file/ASSIGNMENTS_VENGAIAH/FTP_ADAPTER_P2/READ_FILE"
     xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/"
     xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/"
     xmlns:pc="http://xmlns.oracle.com/pcbpel/"
     xmlns:imp1="http://TargetNamespace.com/READ_FILE"
     xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    >
  <plt:partnerLinkType name="Read_plt" >
    <plt:role name="Read_role" >
      <plt:portType name="tns:Read_ptt" />
    </plt:role>
  </plt:partnerLinkType>
    <wsdl:types>
      <schema xmlns="http://www.w3.org/2001/XMLSchema" >
        <import namespace="http://TargetNamespace.com/READ_FILE" schemaLocation="../Schemas/nxsd_schema1.xsd" />
      </schema>
    </wsdl:types>
    <wsdl:message name="Read_msg">
        <wsdl:part name="body" element="imp1:Root-Element"/>
    </wsdl:message>
    <wsdl:portType name="Read_ptt">
        <wsdl:operation name="Read">
            <wsdl:input message="tns:Read_msg"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>
