<wsdl:definitions
     name="DB_Adapter"
     targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/ASSIGNMENTS_VENGAIAH/Data_insert_DB_adapter_p3/DB_Adapter"
     xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/ASSIGNMENTS_VENGAIAH/Data_insert_DB_adapter_p3/DB_Adapter"
     xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/"
     xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/"
     xmlns:top="http://xmlns.oracle.com/pcbpel/adapter/db/top/DB_Adapter"
     xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    >
  <plt:partnerLinkType name="DB_Adapter_plt" >
    <plt:role name="DB_Adapter_role" >
      <plt:portType name="tns:DB_Adapter_ptt" />
    </plt:role>
  </plt:partnerLinkType>
    <wsdl:types>
      <schema xmlns="http://www.w3.org/2001/XMLSchema" >
        <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/top/DB_Adapter" schemaLocation="../Schemas/DB_Adapter_table.xsd" />
      </schema>
    </wsdl:types>
    <wsdl:message name="CustomersCollection_msg">
        <wsdl:part name="CustomersCollection" element="top:CustomersCollection"/>
    </wsdl:message>
    <wsdl:portType name="DB_Adapter_ptt">
        <wsdl:operation name="insert">
            <wsdl:input message="tns:CustomersCollection_msg"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>
